services:
  - type: web
    name: lucknow-dsp-dashboard
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Lucknow.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
